-- PostgreSQL requires newly added enum values to be committed before they are
-- used as defaults or in data updates, so this is intentionally separate.
ALTER TYPE "ReportReason" ADD VALUE IF NOT EXISTS 'OFFENSIVE';
ALTER TYPE "ReportReason" ADD VALUE IF NOT EXISTS 'OFF_TOPIC';
ALTER TYPE "ReportStatus" ADD VALUE IF NOT EXISTS 'PENDING';
ALTER TYPE "ReportStatus" ADD VALUE IF NOT EXISTS 'REVIEWED';
ALTER TYPE "ReportStatus" ADD VALUE IF NOT EXISTS 'ACTION_TAKEN';
ALTER TYPE "ReputationReason" ADD VALUE IF NOT EXISTS 'TOPIC_DOWNVOTED';
ALTER TYPE "ReputationReason" ADD VALUE IF NOT EXISTS 'REPLY_DOWNVOTED';
ALTER TYPE "ReputationReason" ADD VALUE IF NOT EXISTS 'ACCEPTED_ANSWER';
ALTER TYPE "ReputationReason" ADD VALUE IF NOT EXISTS 'ACCEPTED_ANSWER_REVERSED';
ALTER TYPE "ReputationReason" ADD VALUE IF NOT EXISTS 'REPORT_ACTION_TAKEN';
ALTER TYPE "ReputationReason" ADD VALUE IF NOT EXISTS 'REPORT_ACTION_REVERSED';
CREATE TYPE "ForumEditTargetType" AS ENUM ('TOPIC', 'REPLY');
CREATE TYPE "ForumNotificationType" AS ENUM ('REPLY_TO_TOPIC', 'REPLY_TO_YOUR_REPLY', 'MENTION', 'ACCEPTED_ANSWER', 'REPORT_RESOLVED', 'MODERATION_ACTION');
