"use client";

import { useRouter } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { SafeMarkdown } from "./markdown";

type Category = { slug: string; name: Record<"vi" | "en", string> };

export function TopicEditor({ initialCategory = "" }: { initialCategory?: string }) {
  const router = useRouter(); const area = useRef<HTMLTextAreaElement>(null);
  const [categories, setCategories] = useState<Category[]>([]); const [body, setBody] = useState(""); const [tags, setTags] = useState(""); const [suggestions, setSuggestions] = useState<string[]>([]); const [error, setError] = useState(""); const [sending, setSending] = useState(false);
  useEffect(() => { fetch("/api/forum/categories").then((response) => response.json()).then(setCategories).catch(() => undefined); }, []);
  useEffect(() => { const q = tags.split(",").at(-1)?.trim().replace(/^commander:/, "") ?? ""; const timer = setTimeout(() => { if (q.length < 2) { setSuggestions([]); return; } fetch(`/api/codex/commanders?q=${encodeURIComponent(q)}`).then((response) => response.ok ? response.json() : { commanders: [] }).then((data) => setSuggestions(data.commanders.map((item: { slug: string }) => `commander:${item.slug}`))).catch(() => undefined); }, q.length < 2 ? 0 : 200); return () => clearTimeout(timer); }, [tags]);
  function format(before: string, after = before) { const input = area.current; if (!input) return; const start = input.selectionStart; const end = input.selectionEnd; const selected = body.slice(start, end) || "nội dung"; const next = body.slice(0, start) + before + selected + after + body.slice(end); setBody(next); requestAnimationFrame(() => { input.focus(); input.setSelectionRange(start + before.length, start + before.length + selected.length); }); }
  function chooseTag(value: string) { const values = tags.split(","); values[values.length - 1] = ` ${value}`; setTags(values.join(",").replace(/^\s/, "")); setSuggestions([]); }
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSending(true); setError(""); const data = new FormData(event.currentTarget); const response = await fetch("/api/forum/topics", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ categorySlug: data.get("category"), title: data.get("title"), bodyMarkdown: body, tags: tags.split(",").map((item) => item.trim()).filter(Boolean) }) }); const result = await response.json(); setSending(false); if (!response.ok) return setError(result.error ?? "Không thể tạo chủ đề."); router.push(`/forum/topic/${result.topic.slug}`); }
  return <form className="forum-editor" onSubmit={submit}><label>Chuyên mục<select name="category" defaultValue={initialCategory} required><option value="" disabled>Chọn chuyên mục</option>{categories.map((item) => <option key={item.slug} value={item.slug}>{item.name.vi ?? item.slug}</option>)}</select></label><label>Tiêu đề<input name="title" minLength={5} maxLength={240} required /></label><div className="markdown-toolbar"><button type="button" onClick={() => format("**")}>B</button><button type="button" onClick={() => format("*")}><i>I</i></button><button type="button" onClick={() => format("[", "](https://)")}>Link</button><button type="button" onClick={() => format("![mô tả](", ")")}>Ảnh</button><button type="button" onClick={() => format("```\n", "\n```")}>Code</button><button type="button" onClick={() => format("> ", "")}>Trích dẫn</button></div><label>Nội dung Markdown<textarea ref={area} value={body} onChange={(event) => setBody(event.target.value)} minLength={2} required /></label><label>Tags<input value={tags} onChange={(event) => setTags(event.target.value)} placeholder="commander:slug, kvk1" /></label>{suggestions.length ? <div className="tag-suggestions">{suggestions.map((item) => <button type="button" key={item} onClick={() => chooseTag(item)}>{item}</button>)}</div> : null}<section className="markdown-preview"><strong>Xem trước</strong>{body ? <SafeMarkdown>{body}</SafeMarkdown> : <p>Nội dung xem trước sẽ xuất hiện ở đây.</p>}</section>{error && <p className="forum-error">{error}</p>}<button className="button" disabled={sending}>{sending ? "Đang đăng…" : "Đăng chủ đề"}</button></form>;
}
