"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Card } from "@/components/ui";

type Author = { id: string; displayName: string | null; name: string | null };
type Reply = { id: string; parentId: string | null; bodyHtml: string; body: string; score: number; viewerVote: number | null; isAcceptedAnswer: boolean; createdAt: string; editedAt: string | null; author: Author };
type Topic = { id: string; slug: string; title: string; body: string; bodyHtml: string; score: number; viewCount: number; replyCount: number; isPinned: boolean; isLocked: boolean; createdAt: string; editedAt: string | null; author: Author; category: { slug: string }; replies: Reply[]; tags: Array<{ slug: string; isVerified: boolean }>; viewer: { vote: number | null; bookmarked: boolean; subscribed: boolean } };

export function TopicThread({ topicKey, currentUser }: { topicKey: string; currentUser: { id: string; verified: boolean; role: string } | null }) {
  const router = useRouter(); const [topic, setTopic] = useState<Topic | null>(null); const [error, setError] = useState(""); const [sending, setSending] = useState(false); const [replyTo, setReplyTo] = useState<Reply | null>(null);
  const load = useCallback(async () => { const response = await fetch(`/api/forum/topics/${topicKey}`); const json = await response.json(); if (!response.ok) throw new Error(json.error); setTopic(json); }, [topicKey]);
  // eslint-disable-next-line react-hooks/set-state-in-effect -- load updates state only after the API promise resolves.
  useEffect(() => { load().catch((reason: Error) => setError(reason.message)); }, [load]);
  useEffect(() => { if (topic?.id) fetch(`/api/forum/topics/${topic.id}/view`, { method: "POST" }).catch(() => undefined); }, [topic?.id]);
  const grouped = useMemo(() => { const roots = topic?.replies.filter((item) => !item.parentId) ?? []; return roots.map((root) => ({ root, children: topic?.replies.filter((item) => item.parentId === root.id) ?? [] })); }, [topic?.replies]);
  async function vote(targetType: "TOPIC" | "REPLY", targetId: string, value: 1 | -1) {
    if (!currentUser || !topic) return router.push("/auth/signin");
    const previous = targetType === "TOPIC" ? topic.viewer.vote : topic.replies.find((item) => item.id === targetId)?.viewerVote ?? null; const next = previous === value ? null : value; const delta = (next ?? 0) - (previous ?? 0);
    setTopic((current) => current && (targetType === "TOPIC" ? { ...current, score: current.score + delta, viewer: { ...current.viewer, vote: next } } : { ...current, replies: current.replies.map((item) => item.id === targetId ? { ...item, score: item.score + delta, viewerVote: next } : item) }));
    const response = await fetch("/api/forum/vote", { method: next === null ? "DELETE" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ targetType, targetId, ...(next === null ? {} : { value: next === 1 ? "UP" : "DOWN" }) }) });
    if (!response.ok) { setError("Không thể ghi nhận vote."); await load(); }
  }
  async function toggleBookmark() { if (!currentUser || !topic) return router.push("/auth/signin"); const previous = topic.viewer.bookmarked; setTopic({ ...topic, viewer: { ...topic.viewer, bookmarked: !previous } }); const response = await fetch(previous ? `/api/forum/bookmark/${topic.id}` : "/api/forum/bookmark", { method: previous ? "DELETE" : "POST", headers: { "content-type": "application/json" }, body: previous ? undefined : JSON.stringify({ topicId: topic.id }) }); if (!response.ok) setTopic((current) => current ? { ...current, viewer: { ...current.viewer, bookmarked: previous } } : current); }
  async function toggleSubscribe() { if (!currentUser || !topic) return router.push("/auth/signin"); const previous = topic.viewer.subscribed; setTopic({ ...topic, viewer: { ...topic.viewer, subscribed: !previous } }); const response = await fetch(previous ? `/api/forum/subscribe/${topic.id}` : "/api/forum/subscribe", { method: previous ? "DELETE" : "POST", headers: { "content-type": "application/json" }, body: previous ? undefined : JSON.stringify({ topicId: topic.id }) }); if (!response.ok) setTopic((current) => current ? { ...current, viewer: { ...current.viewer, subscribed: previous } } : current); }
  async function sendReply(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!topic) return; const form = event.currentTarget; const bodyMarkdown = String(new FormData(form).get("body") ?? ""); setSending(true); const response = await fetch(`/api/forum/topics/${topic.id}/replies`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ bodyMarkdown, parentReplyId: replyTo?.id }) }); setSending(false); if (!response.ok) { const json = await response.json(); return setError(json.error); } form.reset(); setReplyTo(null); await load(); }
  async function accept(item: Reply) { if (!topic) return; const response = await fetch(`/api/forum/replies/${item.id}/${item.isAcceptedAnswer ? "unaccept" : "accept"}`, { method: "POST" }); if (response.ok) await load(); else setError("Không thể cập nhật câu trả lời đúng."); }
  async function report(targetType: "TOPIC" | "REPLY", targetId: string) { if (!currentUser) return router.push("/auth/signin"); const note = window.prompt("Mô tả ngắn lý do báo cáo:") ?? ""; if (!note) return; const response = await fetch("/api/forum/report", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ targetType, targetId, reason: "OTHER", note }) }); setError(response.ok ? "Đã gửi báo cáo cho đội ngũ kiểm duyệt." : "Không thể gửi báo cáo."); }
  async function editTopic() { if (!topic) return; const title = window.prompt("Tiêu đề:", topic.title); if (!title) return; const bodyMarkdown = window.prompt("Nội dung Markdown:", topic.body); if (!bodyMarkdown) return; const response = await fetch(`/api/forum/topics/${topic.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ title, bodyMarkdown }) }); if (response.ok) await load(); else setError((await response.json()).error ?? "Không thể sửa chủ đề."); }
  async function deleteTopic() { if (!topic || !window.confirm("Xóa mềm chủ đề này?")) return; const response = await fetch(`/api/forum/topics/${topic.id}`, { method: "DELETE" }); if (response.ok) router.push(`/forum/${topic.category.slug}`); else setError("Không thể xóa chủ đề."); }
  async function editReply(item: Reply) { const bodyMarkdown = window.prompt("Nội dung Markdown:", item.body); if (!bodyMarkdown) return; const response = await fetch(`/api/forum/replies/${item.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ bodyMarkdown }) }); if (response.ok) await load(); else setError((await response.json()).error ?? "Không thể sửa câu trả lời."); }
  async function deleteReply(item: Reply) { if (!window.confirm("Xóa mềm câu trả lời này?")) return; const response = await fetch(`/api/forum/replies/${item.id}`, { method: "DELETE" }); if (response.ok) await load(); else setError("Không thể xóa câu trả lời."); }
  async function moderate(action: "pin" | "lock", value: boolean) { if (!topic) return; const response = await fetch(`/api/forum/topics/${topic.id}/${action}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(action === "pin" ? { pinned: value } : { locked: value }) }); if (response.ok) await load(); else setError("Không thể cập nhật kiểm duyệt."); }
  if (error && !topic) return <div className="shell page"><p className="forum-error">{error}</p></div>;
  if (!topic) return <div className="shell page"><p>Đang tải…</p></div>;
  const moderator = Boolean(currentUser && ["MODERATOR", "ADMIN"].includes(currentUser.role)); const isAuthor = currentUser?.id === topic.author.id; const canReply = currentUser?.verified && (!topic.isLocked || moderator);
  function ReplyCard({ item, nested = false }: { item: Reply; nested?: boolean }) { const canManage = currentUser?.id === item.author.id || moderator; return <Card className={`forum-post ${nested ? "forum-child-reply" : ""} ${item.isAcceptedAnswer ? "accepted" : ""}`}><div className="forum-post-meta"><Link href={`/profile/${item.author.id}/activity`}><strong>{item.author.displayName ?? item.author.name ?? "Thành viên"}</strong></Link><span>{new Date(item.createdAt).toLocaleString("vi-VN")}</span>{item.editedAt && <em>đã chỉnh sửa {new Date(item.editedAt).toLocaleString("vi-VN")}</em>}{item.isAcceptedAnswer && <b>✓ Câu trả lời đúng</b>}</div><div className="forum-markdown" dangerouslySetInnerHTML={{ __html: item.bodyHtml }} /><div className="forum-actions"><button className={item.viewerVote === 1 ? "active" : ""} onClick={() => vote("REPLY", item.id, 1)}>▲</button><strong>{item.score}</strong><button className={item.viewerVote === -1 ? "active" : ""} onClick={() => vote("REPLY", item.id, -1)}>▼</button>{canReply && <button onClick={() => setReplyTo(item)}>Trả lời</button>}<button onClick={() => report("REPLY", item.id)}>Báo cáo</button>{isAuthor && <button onClick={() => accept(item)}>{item.isAcceptedAnswer ? "Bỏ đánh dấu" : "Đánh dấu đúng"}</button>}{canManage && <><button onClick={() => editReply(item)}>Sửa</button><button onClick={() => deleteReply(item)}>Xóa</button></>}</div></Card>; }
  return <div className="shell page narrow-page"><p><Link className="text-link" href={`/forum/${topic.category.slug}`}>← Quay lại chuyên mục</Link></p><Card className="forum-post forum-topic-post"><div className="forum-post-meta"><Link href={`/profile/${topic.author.id}/activity`}><strong>{topic.author.displayName ?? topic.author.name ?? "Thành viên"}</strong></Link><span>{new Date(topic.createdAt).toLocaleString("vi-VN")}</span>{topic.editedAt && <em>đã chỉnh sửa {new Date(topic.editedAt).toLocaleString("vi-VN")}</em>}{topic.isPinned && <b>Đã ghim</b>}{topic.isLocked && <b>Đã khóa</b>}</div><h1>{topic.title}</h1><div className="forum-markdown" dangerouslySetInnerHTML={{ __html: topic.bodyHtml }} /><div className="forum-tags">{topic.tags.map((item) => <span key={item.slug}>{item.slug}{item.isVerified ? " ✓" : " · chưa xác minh"}</span>)}</div><div className="forum-actions"><button className={topic.viewer.vote === 1 ? "active" : ""} onClick={() => vote("TOPIC", topic.id, 1)}>▲</button><strong>{topic.score}</strong><button className={topic.viewer.vote === -1 ? "active" : ""} onClick={() => vote("TOPIC", topic.id, -1)}>▼</button><button className={topic.viewer.bookmarked ? "active" : ""} onClick={toggleBookmark}>{topic.viewer.bookmarked ? "Đã lưu" : "Lưu"}</button><button className={topic.viewer.subscribed ? "active" : ""} onClick={toggleSubscribe}>{topic.viewer.subscribed ? "Đang theo dõi" : "Theo dõi"}</button><button onClick={() => report("TOPIC", topic.id)}>Báo cáo</button>{(isAuthor || moderator) && <><button onClick={editTopic}>Sửa</button><button onClick={deleteTopic}>Xóa</button></>}{moderator && <><button onClick={() => moderate("pin", !topic.isPinned)}>{topic.isPinned ? "Bỏ ghim" : "Ghim"}</button><button onClick={() => moderate("lock", !topic.isLocked)}>{topic.isLocked ? "Mở khóa" : "Khóa"}</button></>}<span>{topic.viewCount} lượt xem</span></div></Card>
    <h2 className="forum-reply-title">{topic.replyCount} câu trả lời</h2>{grouped.map(({ root, children }) => <div key={root.id}><ReplyCard item={root} />{children.map((child) => <ReplyCard key={child.id} item={child} nested />)}</div>)}
    {error && <p className="forum-notice" role="status">{error}</p>}{canReply ? <Card className="forum-compose"><h2>{replyTo ? `Trả lời ${replyTo.author.displayName ?? replyTo.author.name}` : "Viết câu trả lời"}</h2>{replyTo && <button onClick={() => setReplyTo(null)}>Hủy trả lời lồng</button>}<form onSubmit={sendReply}><textarea name="body" minLength={2} required placeholder="Bạn có thể dùng Markdown và @mention…" /><button className="button" disabled={sending}>{sending ? "Đang gửi…" : "Gửi câu trả lời"}</button></form></Card> : !currentUser ? <Link className="button" href="/auth/signin">Đăng nhập để trả lời</Link> : !currentUser.verified ? <p className="forum-notice">Xác thực email để trả lời.</p> : <p className="forum-notice">Chủ đề đã khóa.</p>}
  </div>;
}
